## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    !conda install numpy
    !pip install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [7]:
import numpy as np
import pandas as pd
### if for some reason the import gives errors, we need to install numpy using "conda install numpy" via the anaconda prompt
### windows --> start --> anadoconda3 folder --> anaconda prompt

In [2]:
pwd

'C:\\tushar\\training\\Day3'

In [3]:
ls

 Volume in drive C is OSDisk
 Volume Serial Number is 1A86-CB55

 Directory of C:\tushar\training\Day3

04-06-2020  09:05    <DIR>          .
04-06-2020  09:05    <DIR>          ..
03-06-2020  22:38    <DIR>          .ipynb_checkpoints
01-04-2019  12:11           139,290 HR_external.txt
01-04-2019  12:11             4,647 Iris_external.csv
06-04-2019  17:12             4,773 Laliga.csv
03-06-2020  22:38            16,488 LaLigaAnalytics.ipynb
04-06-2020  09:05            23,028 numpy.ipynb
03-06-2020  22:40           593,281 R1-Lab-External_Questions.ipynb
12-03-2019  04:25             4,816 store_sales.csv
02-06-2020  23:00           299,886 SVHN_CNN_Transfer_Updated.ipynb
03-06-2020  13:36               228 testtext.txt
19-11-2019  13:06           420,342 UNet_Class_Version.ipynb
              10 File(s)      1,506,779 bytes
               3 Dir(s)  90,358,992,896 bytes free


In [4]:
### let us understand why numpy
distance = [10,15,17,26]
time = [0.3,0.47,.55,1.2]

In [5]:
speed = distance/time
# distance/time

### we confront an error list 

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
## solving the above problem via numpy
my_distance_arr = np.array(distance)

In [9]:
my_distance_arr

array([10, 15, 17, 26])

In [10]:
my_time_arr = np.array(time)
my_time_arr

array([0.3 , 0.47, 0.55, 1.2 ])

In [11]:
my_distance_arr/my_time_arr

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [12]:
### what if the number of elements are different in the arrays
distance = [10,15,17,26,100]
time = [0.3,0.47,.55,1.2]
my_distance_arr = np.array(distance)
my_time_arr = np.array(time)
my_distance_arr/my_time_arr

### results in an error

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [13]:
mylist=[1,2,3]

In [14]:
nmylist= np.array(mylist)

In [15]:
nmylist.shape

(3,)

In [16]:
len(nmylist)

3

In [17]:
nmylist.ndim

1

## 2 dimensional numpy arrays - matrix

In [18]:
### create a matrix
### we can use a list to build a matrix - list of lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_matrix))
print(my_matrix)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [19]:
## create a numpy array from list
my_num_arr2 =  np.array(my_matrix)
print(my_num_arr2)
print(type(my_num_arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [20]:
### dimension
my_num_arr2.ndim

2

In [21]:
###shape of array
my_num_arr2.shape

(3, 3)

In [22]:
mylisnew = ['5.',1,2,3]
np.array(mylisnew)

array(['5.', '1', '2', '3'], dtype='<U2')

In [23]:
### create a numpy array from a tuple
my_tuple = ((1,2),(3,4),(5,6))
my_tup_arr = np.array(my_tuple)
print(my_tup_arr)
print(type(my_tup_arr))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [24]:
my_tup_arr[0][0]=23

In [25]:
print(my_tup_arr)

[[23  2]
 [ 3  4]
 [ 5  6]]


### Creating numpy arrays from files

In [26]:
store_sales = pd.read_csv("store_sales.csv")

In [27]:
store_sales.head()

store_id        city  Jan  Feb  Mar  Apr  May  Jun  July  Aug  Sep  Oct  \
0      S_1       Texas    8   20   13   21   17   20    24   17   16    9   
1      S_2  California   12   19   15   15   11   19     7   15   10   11   
2      S_3  California   16   16   14   19   23    6    13   13   15   14   
3      S_4       Texas    8   18   13   10   14   14     6    8    8   18   
4      S_5       Texas   19    5   24    9    5   24    10    5   24   15   

   Nov  Dec  
0    7    6  
1   21   19  
2   24    8  
3    7   11  
4    6   13

In [30]:
sales_mat = np.array(store_sales.iloc[:,2:])

In [31]:
sales_mat

array([[ 8, 20, 13, ...,  9,  7,  6],
       [12, 19, 15, ..., 11, 21, 19],
       [16, 16, 14, ..., 14, 24,  8],
       ...,
       [16,  9,  6, ..., 22, 17, 22],
       [18, 16,  9, ..., 17, 19, 10],
       [ 5, 23, 17, ..., 20,  5,  9]], dtype=int64)

In [32]:
sales_mat.shape

(100, 12)

In [33]:
sales_mat.ndim

2

In [34]:
sales_mat = np.array(store_sales.iloc[2:5:2,2:6:2])

In [35]:
sales_mat

array([[16, 14],
       [19, 24]], dtype=int64)

### situations where we will need to generate arrays 

## built in methods in numpy

arange - returns evenly spaced values with in a given interval
arange - array range
helps in auto number generation

syntax of arange - start,stop,step
np.arange(start,stop,step)

In [36]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
np.arange(0,50).ndim

1

In [38]:
np.arange(0,50).shape

(50,)

In [39]:
np.zeros(3)

array([0., 0., 0.])

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.ones(3)*899

array([899., 899., 899.])

In [46]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
### creating arrays more than 3D arrays
np_3d=np.ones((5,5,3))
print(np_3d)
print(np_3d.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3


### generating random integers
#####  random is a library under numpy for generating random integers 

In [47]:
### generate random number between 1 and 100
np.random.randint(1,100)

43

In [48]:
### generate 50 random numbers between 1 and 100
### startnumber , ending number and number of numbers
np.random.randint(1,100,50)

array([ 8, 43, 53, 40, 61, 76, 44, 35, 18, 58,  7, 95, 72, 12, 96, 66, 29,
       14, 70, 78, 91, 36, 32, 12,  9, 12, 22, 82, 76, 88, 51, 70, 24, 18,
       27, 47,  5, 99, 45, 59, 68, 14, 53,  6, 42, 35, 74, 32, 72, 13])

In [ ]:
print(type(np.random.randint(1,100,10)))

## numpy Operions

In [49]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr + arr   #[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
arr * arr       #### multiplies two arrays together

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [56]:
arradd = arr + 100        #### adds 100 to all elements in array

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arradd

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [59]:
arr * 100         #### multiplies 100 to all elements in array

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [60]:
arr / arr #### note the nan (not a number) in the first element of result

C:\Users\tgawade\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
1/arr       #### note inf in the output indicating infinity

C:\Users\tgawade\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [62]:
np.sqrt(arr)       ### sqrt of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [63]:
np.max(arr)        #### max

10

In [64]:
np.cos(arr)       #### sin

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [65]:
### create an ndarray that contains number of hours worked on weekdays
### hourly rate is 15 USD
#my_list = [7,9,9,11,8]
#np_daily_wage = np.array(my_list)
np_daily_wage = np.array([7,9,9,11,8]) * 15
np_daily_wage

array([105, 135, 135, 165, 120])

In [66]:
### calculate total of 5 days
sum(np_daily_wage)

660

In [67]:
#### hours spent every week
np_weekly_hrs = np.array([23,41,55,60,40])

In [68]:
np_weekly_hrs

array([23, 41, 55, 60, 40])

In [69]:
### extract week more than 40
np_weekly_hrs[np_weekly_hrs > 40]

array([41, 55, 60])

In [83]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [85]:
type(cyclist_trials[0][0])

numpy.int32

In [ ]:
cyclist_trials[start:end:step,start:end:step]

In [74]:
slice_cyc_trial = cyclist_trials[:,1:3]

In [75]:
slice_cyc_trial

array([[15, 17],
       [11, 21]])

In [76]:
for x in cyclist_trials:
    print(x)

[10 15 17 26]
[12 11 21 24]


In [77]:
import numpy as np
x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], np.int32)
np.savetxt("testtext.txt", x)

In [78]:
mydataread = np.loadtxt('testtext.txt')

In [82]:
type(mydataread[0][0])

numpy.float64

In [87]:
my_list1 = [1,2,3,4,5,5,7]
my_list2 = [1,2,3,3,4,5,6]

In [88]:
mylstarr1 = np.array(my_list1)

In [89]:
mylstarr2 = np.array(my_list2)

In [90]:
mylstarr1/mylstarr2

array([1.        , 1.        , 1.        , 1.33333333, 1.25      ,
       1.        , 1.16666667])

In [91]:
###3 linearly (Equal) sapced data elements
np.linspace(4,15,12)  

### outputs a 2d array with number of evenly spaced points from 0 to 5. 10 indicates the number of such points

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [92]:
np.eye(4) #ientity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
np.random.rand(10)  ### creates one dim array of 10 evenly random numbers between 0 and 10 excluding 0 and 1

array([0.99327551, 0.21173138, 0.67348006, 0.56880815, 0.71731328,
       0.56395401, 0.82077173, 0.73804722, 0.42898283, 0.62326331])

In [94]:
np.random.randint(1,100)  ### returns random integer from 1 to 100. includes 1 and excludes 100

56

In [95]:
np.random.randint(1,100,10)  ### returns 10 random integer from 1 to 100 

array([31, 18, 80, 51,  2, 33, 99, 41, 92,  3])

In [96]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [97]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
arr.reshape(5,5).argmax()

24

In [99]:
ranarr1 = np.random.randint(0,50,10)
ranarr1

array([47, 44, 36, 49, 36, 22, 31, 29,  4, 34])

In [100]:
ranarr1.argmax()

3

In [101]:
ranarr1.argmin()

8

In [102]:
#### to find the dimension of an array
np_city =  np.array(['nyc','la','houston'])

In [103]:
np_city.shape 

(3,)

In [104]:
np_countries = np.array([['brazil','portugal','morrocco'],['egypt','iran','spain'],['russia','uae','argentina']])

In [105]:
np_countries.shape

(3, 3)

In [106]:
np_countries

array([['brazil', 'portugal', 'morrocco'],
       ['egypt', 'iran', 'spain'],
       ['russia', 'uae', 'argentina']], dtype='<U9')

In [107]:
array_2d = np.array([[5,10,15],[20,25,30],[34,49,29]])

In [108]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [34, 49, 29]])

In [109]:
array_2d.shape

(3, 3)

In [110]:
array_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [111]:
print(array_2d[1:])

[[20 25 30]
 [34 49 29]]


In [112]:
array_2d[1:,1:]

array([[25, 30],
       [49, 29]])

In [113]:
threeD_array = np.arange(27).reshape(3,3,3)

In [114]:
threeD_array        #### watch for number of square brackets in the resulting list

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [118]:
#threeD_array [indexes of third dimension(start:stop:step), row(start:stop:step), column(start:end:step)]

threeD_array[0:2,1:3,1:3] #1.7,8,16,17
                          #2.13,16 #3.4,7 #4.6,8

array([[[ 4,  5],
        [ 7,  8]],

       [[13, 14],
        [16, 17]]])

## Broadcasting
## If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

In [119]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:' )
print (a) 
print ('\n')  
   
print ('Second array:' )
print (b )
print ('\n')  
   
print ('First Array + Second Array' )
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## Transpose and Iterator 

In [120]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print ('Original array is:')
print (a) 
print ('\n')  
   
print ('Transpose of the original array is:' )
b = a.T 
print (b) 
print ('\n'  )
   
print ('Modified array is:' )
for x in np.nditer(b): 
   print (x),

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


## Modifying Array Values
### The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. This will enable modifying array elements using this iterator.

In [121]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print ('Modified array is:')
print (a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


## Arithmatic Operations

In [122]:
import numpy as np
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print ('First array:' )
print (a) 
print ('\n')  

print ('Second array:' )
b = np.array([10,10,10]) 
print (b) 
print ('\n'  )

print ('Add the two arrays:' )
print (np.add(a,b)) 
print ('\n')  

print ('Subtract the two arrays:' )
print (np.subtract(a,b)) 
print ('\n')  

print ('Multiply the two arrays:' )
print (np.multiply(a,b) )
print ('\n')  

print ('Divide the two arrays:' )
print (np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [ ]:
# Try slicng with 4 D array
#How to flatten a matrix
# Raval vs flatten