In [31]:
# Input
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)

In [30]:
# Input
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
# df

# Show all available options
# pd.describe_option()

In [29]:
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)

# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
# or
df.applymap(lambda x: '%.4f' % x)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0000
1  0.3540
2  0.0371
3  0.0000


In [32]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [33]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [34]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

0

In [ ]:
# Input
import pandas as pd
import numpy as np
ser = pd.Series(np.random.randint(1, 100, 15))

# Solution
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
np.argwhere(ser > ser.mean())[1]

In [38]:
# Input
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution
# print row sums
rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]

In [39]:
# Input
ser = pd.Series(np.logspace(-2, 2, 30))

# Solution
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


In [40]:
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0 -19   0  39 -11  48  33 -15  34  43  22
1 -18  30 -16  34  35  47  21  26  -8  -5
2  39  -9  31   8  27 -10  33  21  27  32
3  33  13  14  35  31  10  -3 -10  20  -4
4 -13 -17  42  -3  13  19 -14 -10  25  16
5 -16  38   1   3  28  17  46   7  25  11
6  -7  -6  -9  -7  44  34  18  13 -12   8
7   0 -14  15  36  48  14  -5 -17  28  34
8  21 -18   2  26 -19  23  10  25  24  34
9  33  48   0 -17  19 -20  33   2  18  43
[[39. 48. 33. 34. 43. 22. 30. 34.]
 [35. 47. 21. 26. 39. 31.  8. 27.]
 [33. 21. 27. 32. 33. 13. 14. 35.]
 [31. 10. 20. 42. 13. 19. 25. 16.]
 [38.  3. 28. 17. 46.  7. 25. 11.]
 [44. 34. 18. 13.  8. 15. 36. 48.]
 [14. 28. 34. 21. 26. 23. 10. 25.]
 [24. 34. 33. 48. 19. 33. 18. 43.]]


In [15]:
# Input
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [17]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [18]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  1


In [19]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -1.16 -1.84 -0.21 -1.01  1.07  0.95 -0.87 -0.50  0.58  0.77
1  0.87 -0.38 -1.53  1.50 -0.95 -0.77 -1.01  1.23  0.51 -0.92
2  1.62  1.01 -0.44  0.24  1.15  0.20 -0.52 -0.65 -0.13 -0.22
3  0.58  0.35  1.57 -1.20  1.07  0.91  0.71  0.93 -1.42 -1.26
4 -1.05 -0.51 -0.01 -0.28 -1.07  0.41 -0.76  0.30  0.72  0.32
5  0.27  0.61  1.30  0.76 -0.73 -1.63 -0.30 -1.19  1.04 -1.03
6 -0.30 -0.45 -0.47 -0.89 -0.85  0.91  1.29 -1.16  0.33  1.16
7 -0.82  1.21 -0.21  0.88  0.30 -0.99  1.45  1.05 -1.63  1.19
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  1.00  1.00  0.57  0.93  0.03  0.00  0.94  0.72  0.17  0.17
1  0.27  0.52  1.00  0.00  0.95  0.67  1.00  0.00  0.20  0.86
2  0.00  0.07  0.65  0.47  0.00  0.29  0.80  0.78  0.44  0.57
3  0.37  0.28  0.00  1.00  0.03  0.01  0.30  0.12  0.92  1.00
4  0.96  0.57  0.51  0.66  1.00  0.21  0.90  0.38  0.12  0.36
5  0.48  0.20  0.09  0.27  0.85  1.00  0.71 

In [25]:
# Input
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0